language: cpp

branches:
  only:
    - master

env:
  - CONFIG=release

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required


before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get update -qq
      sudo apt-get install -qq libhidapi-dev libhidapi-hidraw0
    fi

before_script:
  - mkdir build
  - cd build

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      chmod +x Qt-build/travis-build-linux.sh
      TAG_NAME=${TRAVIS_TAG} ./Qt-build/travis-build-linux.sh
    fi