language: cpp

os:
  - linux

branches:
  only:
    - master

env:
  matrix:
    - CONFIG=release

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get update -qq
      sudo apt-get install -qq libhidapi-dev libhidapi-hidraw0 qt5-default
    fi

before_script:
  - mkdir build
  - cd build

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      qmake ../FlightController/FlightController.pro -r -spec linux-g++-64
    fi